
-- ---------------------------------------------------------------------
-- 0. Pré-checagem (falha cedo com mensagem clara)
-- ---------------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.usuarios WHERE email IS NOT NULL
               GROUP BY lower(email) HAVING count(*) > 1) THEN
        RAISE EXCEPTION 'usuarios: e-mails duplicados (ignorando maiúsculas). Corrija antes de migrar.';
    END IF;
END $$;

-- ---------------------------------------------------------------------
-- 1. Funções utilitárias
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.definir_atualizado_em()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $$
BEGIN
    NEW.atualizado_em := now();
    RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------
-- 2. empresas (tenant = 1 conta/banco Secullum)
-- ---------------------------------------------------------------------
CREATE TABLE public.empresas (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                    text        NOT NULL,
    secullum_usuario        text,
    secullum_senha_cripto   text,                 -- AES-256-GCM na aplicação: iv:tag:cifra (hex)
    secullum_banco_id       text,                 -- header secullumidbancoselecionado
    sincronizacao_solicitada_em timestamptz,
    sincronizado_em         timestamptz,
    ativo                   boolean     NOT NULL DEFAULT true,
    criado_em               timestamptz NOT NULL DEFAULT now(),
    atualizado_em           timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT empresas_nome_uk          UNIQUE (nome),
    CONSTRAINT empresas_banco_uk         UNIQUE (secullum_banco_id),
    CONSTRAINT empresas_nome_chk         CHECK (btrim(nome) <> ''),
    CONSTRAINT empresas_credenciais_chk  CHECK ((secullum_usuario IS NULL) = (secullum_senha_cripto IS NULL))
);
CREATE TRIGGER trg_empresas_atualizado_em
    BEFORE UPDATE ON public.empresas
    FOR EACH ROW EXECUTE FUNCTION public.definir_atualizado_em();

-- Tenant inicial (necessário para o backfill de usuarios)
INSERT INTO public.empresas (nome) VALUES ('Transcouto')
ON CONFLICT (nome) DO NOTHING;

-- ---------------------------------------------------------------------
-- 3. usuarios (existente) — colunas novas, backfill, depois constraints
-- ---------------------------------------------------------------------
ALTER TABLE public.usuarios
    ADD COLUMN IF NOT EXISTS perfil            text,
    ADD COLUMN IF NOT EXISTS empresa_id        integer REFERENCES public.empresas(id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS deve_trocar_senha boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS token_versao      integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ultimo_login_em   timestamptz;

ALTER TABLE public.usuarios ALTER COLUMN email DROP NOT NULL;

-- 3.1 CPF: canonizar para 11 dígitos em texto (hoje pode estar como número)
DO $$
DECLARE
    v_tipo text;
BEGIN
    SELECT data_type INTO v_tipo
      FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = 'usuarios' AND column_name = 'cpf';

    IF v_tipo IN ('integer', 'bigint', 'numeric') THEN
        ALTER TABLE public.usuarios ALTER COLUMN cpf TYPE varchar(11)
            USING CASE WHEN cpf IS NULL THEN NULL
                       WHEN length(cpf::text) <= 11 THEN lpad(cpf::text, 11, '0')
                       ELSE cpf::text END;          -- >11 falha no cast: revisar manualmente
    ELSIF v_tipo IS NOT NULL THEN
        UPDATE public.usuarios
           SET cpf = NULLIF(regexp_replace(cpf, '[^0-9]', '', 'g'), '')
         WHERE cpf IS NOT NULL;
        ALTER TABLE public.usuarios ALTER COLUMN cpf TYPE varchar(11);
    END IF;
END $$;

-- 3.2 Backfill de perfil/empresa (ajuste a regra de domínio se necessário)
UPDATE public.usuarios
   SET perfil = CASE WHEN lower(email) LIKE '%@scaleia.ai' THEN 'admin' ELSE 'gestor' END
 WHERE perfil IS NULL;

UPDATE public.usuarios
   SET empresa_id = (SELECT id FROM public.empresas WHERE nome = 'Transcouto')
 WHERE perfil <> 'admin' AND empresa_id IS NULL;

UPDATE public.usuarios SET ativo = true WHERE ativo IS NULL;

-- 3.3 Constraints só depois do backfill
ALTER TABLE public.usuarios
    ALTER COLUMN perfil SET DEFAULT 'gestor',
    ALTER COLUMN perfil SET NOT NULL,
    ALTER COLUMN ativo  SET DEFAULT true,
    ALTER COLUMN ativo  SET NOT NULL,
    ADD CONSTRAINT usuarios_perfil_chk         CHECK (perfil IN ('admin', 'rh', 'gestor')),
    ADD CONSTRAINT usuarios_perfil_empresa_chk CHECK ((perfil = 'admin') = (empresa_id IS NULL)),
    ADD CONSTRAINT usuarios_cpf_chk            CHECK (cpf IS NULL OR cpf ~ '^[0-9]{11}$'),
    ADD CONSTRAINT usuarios_login_chk          CHECK (email IS NOT NULL OR cpf IS NOT NULL),
    ADD CONSTRAINT usuarios_id_empresa_uk      UNIQUE (id, empresa_id);

-- nome não é único (dois "João Silva" são possíveis)
ALTER TABLE public.usuarios DROP CONSTRAINT IF EXISTS usuarios_nome_key;

CREATE UNIQUE INDEX IF NOT EXISTS usuarios_email_lower_uk ON public.usuarios (lower(email));
CREATE UNIQUE INDEX IF NOT EXISTS usuarios_cpf_uk        ON public.usuarios (cpf) WHERE cpf IS NOT NULL;
CREATE INDEX        IF NOT EXISTS usuarios_empresa_idx   ON public.usuarios (empresa_id);

DROP TRIGGER IF EXISTS trg_usuarios_atualizado_em ON public.usuarios;
CREATE TRIGGER trg_usuarios_atualizado_em
    BEFORE UPDATE ON public.usuarios
    FOR EACH ROW EXECUTE FUNCTION public.definir_atualizado_em();

-- ---------------------------------------------------------------------
-- 4. configuracoes (1:1 empresa) — editável pelo cliente sem deploy
-- ---------------------------------------------------------------------
CREATE TABLE public.configuracoes (
    empresa_id                      integer     PRIMARY KEY REFERENCES public.empresas(id) ON DELETE CASCADE,
    dia_semana_extracao             smallint    NOT NULL DEFAULT 3,          -- 0=dom … 3=qua
    hora_extracao                   time        NOT NULL DEFAULT '06:00',
    dia_fechamento_mes              smallint    NOT NULL DEFAULT 25,
    dias_apos_fechamento_mes        smallint    NOT NULL DEFAULT 2,          -- 25 fecha, 26 ajusta, 27 extrai
    origem_horas_pagas              text        NOT NULL DEFAULT 'teto',
    teto_horas_pagas_minutos        integer     NOT NULL DEFAULT 0,
    teto_periodicidade              text        NOT NULL DEFAULT 'mensal',
    alerta_saldo_positivo_minutos   integer     NOT NULL DEFAULT 600,
    alerta_saldo_negativo_minutos   integer     NOT NULL DEFAULT 600,
    fuso_horario                    text        NOT NULL DEFAULT 'America/Sao_Paulo',
    cota_calcular_por_hora          smallint    NOT NULL DEFAULT 90,
    atualizado_por                  integer     REFERENCES public.usuarios(id) ON DELETE SET NULL,
    atualizado_em                   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT configuracoes_dia_semana_chk  CHECK (dia_semana_extracao BETWEEN 0 AND 6),
    CONSTRAINT configuracoes_dia_mes_chk     CHECK (dia_fechamento_mes BETWEEN 1 AND 28),
    CONSTRAINT configuracoes_dias_apos_chk   CHECK (dias_apos_fechamento_mes BETWEEN 0 AND 10),
    CONSTRAINT configuracoes_origem_chk      CHECK (origem_horas_pagas IN ('teto', 'coluna_secullum')),
    CONSTRAINT configuracoes_teto_chk        CHECK (teto_horas_pagas_minutos >= 0),
    CONSTRAINT configuracoes_period_chk      CHECK (teto_periodicidade IN ('semanal', 'mensal')),
    CONSTRAINT configuracoes_alertas_chk     CHECK (alerta_saldo_positivo_minutos > 0 AND alerta_saldo_negativo_minutos > 0),
    CONSTRAINT configuracoes_cota_chk        CHECK (cota_calcular_por_hora BETWEEN 1 AND 100)
);
CREATE TRIGGER trg_configuracoes_atualizado_em
    BEFORE UPDATE ON public.configuracoes
    FOR EACH ROW EXECUTE FUNCTION public.definir_atualizado_em();

INSERT INTO public.configuracoes (empresa_id)
SELECT id FROM public.empresas WHERE nome = 'Transcouto'
ON CONFLICT (empresa_id) DO NOTHING;

-- ---------------------------------------------------------------------
-- 5. mapeamento_colunas — coluna do /Calcular -> campo
-- ---------------------------------------------------------------------
CREATE TABLE public.mapeamento_colunas (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id       integer     NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    coluna_secullum  text        NOT NULL,
    campo            text        NOT NULL,
    criado_em        timestamptz NOT NULL DEFAULT now(),
    atualizado_em    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT mapeamento_colunas_uk        UNIQUE (empresa_id, coluna_secullum),
    CONSTRAINT mapeamento_colunas_campo_chk CHECK (campo IN ('extra', 'negativa', 'pagas', 'saldo_banco', 'ignorar'))
);
CREATE UNIQUE INDEX mapeamento_colunas_saldo_uk
    ON public.mapeamento_colunas (empresa_id) WHERE campo = 'saldo_banco';
CREATE TRIGGER trg_mapeamento_colunas_atualizado_em
    BEFORE UPDATE ON public.mapeamento_colunas
    FOR EACH ROW EXECUTE FUNCTION public.definir_atualizado_em();

-- ---------------------------------------------------------------------
-- 6. unidades — /Empresas da FriPonto + "de x para"
-- ---------------------------------------------------------------------
CREATE TABLE public.unidades (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id       integer     NOT NULL REFERENCES public.empresas(id) ON DELETE RESTRICT,
    documento        varchar(14) NOT NULL,       -- CNPJ (alfanumérico) ou CPF, sem máscara
    razao_social     text        NOT NULL,
    nome_exibicao    text,                       -- NULL = ainda não mapeada (não aparece p/ gestor)
    ativo            boolean     NOT NULL DEFAULT true,
    sincronizado_em  timestamptz,
    criado_em        timestamptz NOT NULL DEFAULT now(),
    atualizado_em    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT unidades_documento_uk   UNIQUE (empresa_id, documento),
    CONSTRAINT unidades_id_empresa_uk  UNIQUE (id, empresa_id),
    CONSTRAINT unidades_documento_chk  CHECK (documento ~ '^([0-9]{11}|[0-9A-Z]{12}[0-9]{2})$'),
    CONSTRAINT unidades_nome_chk       CHECK (nome_exibicao IS NULL OR btrim(nome_exibicao) <> '')
);
CREATE UNIQUE INDEX unidades_nome_exibicao_uk
    ON public.unidades (empresa_id, lower(nome_exibicao)) WHERE nome_exibicao IS NOT NULL;
CREATE TRIGGER trg_unidades_atualizado_em
    BEFORE UPDATE ON public.unidades
    FOR EACH ROW EXECUTE FUNCTION public.definir_atualizado_em();

-- ---------------------------------------------------------------------
-- 7. usuario_unidades — gestor x unidade (mesma empresa garantida por FK)
-- ---------------------------------------------------------------------
CREATE TABLE public.usuario_unidades (
    usuario_id  integer     NOT NULL,
    unidade_id  integer     NOT NULL,
    empresa_id  integer     NOT NULL,
    criado_por  integer     REFERENCES public.usuarios(id) ON DELETE SET NULL,
    criado_em   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (usuario_id, unidade_id),
    CONSTRAINT usuario_unidades_usuario_fk FOREIGN KEY (usuario_id, empresa_id)
        REFERENCES public.usuarios (id, empresa_id) ON DELETE CASCADE,
    CONSTRAINT usuario_unidades_unidade_fk FOREIGN KEY (unidade_id, empresa_id)
        REFERENCES public.unidades (id, empresa_id) ON DELETE CASCADE
);
CREATE INDEX usuario_unidades_unidade_idx ON public.usuario_unidades (unidade_id);

-- ---------------------------------------------------------------------
-- 8. colaboradores — /Funcionarios (chave CPF)
-- ---------------------------------------------------------------------
CREATE TABLE public.colaboradores (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id       integer     NOT NULL,
    unidade_id       integer     NOT NULL,
    secullum_id      integer,
    nome             text        NOT NULL,
    cpf              varchar(11) NOT NULL,
    numero_folha     text,
    departamento     text,
    funcao           text,
    data_admissao    date,
    data_demissao    date,
    ativo            boolean     NOT NULL DEFAULT true,
    sincronizado_em  timestamptz,
    criado_em        timestamptz NOT NULL DEFAULT now(),
    atualizado_em    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT colaboradores_cpf_uk      UNIQUE (empresa_id, cpf),
    CONSTRAINT colaboradores_cpf_chk     CHECK (cpf ~ '^[0-9]{11}$'),
    CONSTRAINT colaboradores_datas_chk   CHECK (data_demissao IS NULL OR data_admissao IS NULL OR data_demissao >= data_admissao),
    CONSTRAINT colaboradores_unidade_fk  FOREIGN KEY (unidade_id, empresa_id)
        REFERENCES public.unidades (id, empresa_id) ON DELETE RESTRICT
);
CREATE INDEX colaboradores_unidade_ativos_idx ON public.colaboradores (unidade_id) WHERE ativo;
CREATE TRIGGER trg_colaboradores_atualizado_em
    BEFORE UPDATE ON public.colaboradores
    FOR EACH ROW EXECUTE FUNCTION public.definir_atualizado_em();

-- ---------------------------------------------------------------------
-- 9. ciclos — rodada de extração da empresa (semana ou fechamento do mês)
-- ---------------------------------------------------------------------
CREATE TABLE public.ciclos (
    id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id            integer     NOT NULL REFERENCES public.empresas(id) ON DELETE RESTRICT,
    tipo                  text        NOT NULL DEFAULT 'semanal',
    periodo_inicio        date        NOT NULL,
    data_referencia       date        NOT NULL,
    gatilho_previsto_em   timestamptz NOT NULL,
    gatilho_em            timestamptz NOT NULL,
    gatilho_ajustado_por  integer     REFERENCES public.usuarios(id) ON DELETE SET NULL,
    gatilho_ajustado_em   timestamptz,
    criado_em             timestamptz NOT NULL DEFAULT now(),
    atualizado_em         timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ciclos_ref_uk         UNIQUE (empresa_id, data_referencia),
    CONSTRAINT ciclos_id_empresa_uk  UNIQUE (id, empresa_id),
    CONSTRAINT ciclos_tipo_chk       CHECK (tipo IN ('semanal', 'fechamento_mes')),
    CONSTRAINT ciclos_janela_chk     CHECK (data_referencia >= periodo_inicio
                                            AND data_referencia <= periodo_inicio + 30)  -- /Calcular: máx. 1 mês
);
CREATE INDEX ciclos_gatilho_idx ON public.ciclos (empresa_id, gatilho_em);
CREATE TRIGGER trg_ciclos_atualizado_em
    BEFORE UPDATE ON public.ciclos
    FOR EACH ROW EXECUTE FUNCTION public.definir_atualizado_em();

-- ---------------------------------------------------------------------
-- 10. fechamentos — status de cada unidade no ciclo (fila retomável)
-- ---------------------------------------------------------------------
CREATE TABLE public.fechamentos (
    id                           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ciclo_id                     integer     NOT NULL,
    empresa_id                   integer     NOT NULL,
    unidade_id                   integer     NOT NULL,
    status                       text        NOT NULL DEFAULT 'pendente',
    tentativas                   smallint    NOT NULL DEFAULT 0,
    proxima_tentativa_em         timestamptz,
    heartbeat_em                 timestamptz,
    total_colaboradores          integer,
    teto_aplicado_minutos        integer,
    teto_periodicidade_aplicada  text,
    publicado_em                 timestamptz,
    criado_em                    timestamptz NOT NULL DEFAULT now(),
    atualizado_em                timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fechamentos_uk          UNIQUE (ciclo_id, unidade_id),
    CONSTRAINT fechamentos_ciclo_fk    FOREIGN KEY (ciclo_id, empresa_id)
        REFERENCES public.ciclos (id, empresa_id) ON DELETE RESTRICT,
    CONSTRAINT fechamentos_unidade_fk  FOREIGN KEY (unidade_id, empresa_id)
        REFERENCES public.unidades (id, empresa_id) ON DELETE RESTRICT,
    CONSTRAINT fechamentos_status_chk  CHECK (status IN ('pendente', 'processando', 'sucesso', 'falhou', 'cancelado')),
    CONSTRAINT fechamentos_publ_chk    CHECK (status <> 'sucesso' OR publicado_em IS NOT NULL),
    CONSTRAINT fechamentos_teto_chk    CHECK (teto_aplicado_minutos IS NULL OR teto_aplicado_minutos >= 0),
    CONSTRAINT fechamentos_period_chk  CHECK (teto_periodicidade_aplicada IS NULL
                                              OR teto_periodicidade_aplicada IN ('semanal', 'mensal'))
);
CREATE INDEX fechamentos_fila_idx       ON public.fechamentos (status) WHERE status IN ('pendente', 'processando');
CREATE INDEX fechamentos_publicados_idx ON public.fechamentos (unidade_id) WHERE status = 'sucesso';
CREATE TRIGGER trg_fechamentos_atualizado_em
    BEFORE UPDATE ON public.fechamentos
    FOR EACH ROW EXECUTE FUNCTION public.definir_atualizado_em();

-- ---------------------------------------------------------------------
-- 11. execucoes_extracao — log de tentativas (painel 5.4)
-- ---------------------------------------------------------------------
CREATE TABLE public.execucoes_extracao (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechamento_id        integer     NOT NULL REFERENCES public.fechamentos(id) ON DELETE CASCADE,
    disparo              text        NOT NULL DEFAULT 'automatico',
    disparado_por        integer     REFERENCES public.usuarios(id) ON DELETE SET NULL,
    status               text        NOT NULL DEFAULT 'processando',
    total_colaboradores  integer     NOT NULL DEFAULT 0,
    processados          integer     NOT NULL DEFAULT 0,
    com_erro             integer     NOT NULL DEFAULT 0,
    mensagem_erro        text,
    iniciado_em          timestamptz NOT NULL DEFAULT now(),
    finalizado_em        timestamptz,
    CONSTRAINT execucoes_disparo_chk  CHECK (disparo IN ('automatico', 'manual')),
    CONSTRAINT execucoes_autor_chk    CHECK (disparo = 'manual' OR disparado_por IS NULL),
    CONSTRAINT execucoes_status_chk   CHECK (status IN ('processando', 'sucesso', 'falhou', 'interrompida')),
    CONSTRAINT execucoes_fim_chk      CHECK ((status = 'processando') = (finalizado_em IS NULL)),
    CONSTRAINT execucoes_contagem_chk CHECK (processados >= 0 AND com_erro >= 0 AND total_colaboradores >= 0)
);
CREATE INDEX execucoes_fechamento_idx ON public.execucoes_extracao (fechamento_id, iniciado_em DESC);
CREATE UNIQUE INDEX execucoes_uma_ativa_uk
    ON public.execucoes_extracao (fechamento_id) WHERE status = 'processando';

-- ---------------------------------------------------------------------
-- 12. registros_horas — snapshot congelado (criada antes de execucao_erros
--     só por legibilidade; não há dependência entre elas)
-- ---------------------------------------------------------------------
CREATE TABLE public.registros_horas (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechamento_id            integer NOT NULL REFERENCES public.fechamentos(id) ON DELETE CASCADE,
    colaborador_id           integer NOT NULL REFERENCES public.colaboradores(id) ON DELETE RESTRICT,
    extra_periodo            integer NOT NULL DEFAULT 0,
    negativa_periodo         integer NOT NULL DEFAULT 0,
    pagas_periodo            integer NOT NULL DEFAULT 0,
    banco_periodo            integer NOT NULL DEFAULT 0,
    extra_semana             integer NOT NULL DEFAULT 0,   -- pode ser < 0 (correção retroativa)
    negativa_semana          integer NOT NULL DEFAULT 0,
    pagas_semana             integer NOT NULL DEFAULT 0,
    banco_semana             integer NOT NULL DEFAULT 0,
    saldo_banco_total        integer NOT NULL DEFAULT 0,
    base_semana_registro_id  bigint  REFERENCES public.registros_horas(id) ON DELETE SET NULL,
    dados_brutos             jsonb   NOT NULL,
    criado_em                timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT registros_horas_uk          UNIQUE (fechamento_id, colaborador_id),
    CONSTRAINT registros_horas_periodo_chk CHECK (extra_periodo >= 0 AND negativa_periodo >= 0
                                                  AND pagas_periodo >= 0 AND banco_periodo >= 0)
);
CREATE INDEX registros_horas_colaborador_idx ON public.registros_horas (colaborador_id);

-- Congelamento: fechamento publicado não muda (reabrir = mudar status antes)
CREATE OR REPLACE FUNCTION public.impedir_alteracao_publicado()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_catalog
AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.fechamentos f
                WHERE f.id = OLD.fechamento_id AND f.status = 'sucesso') THEN
        RAISE EXCEPTION 'registros_horas: fechamento % já publicado (congelado)', OLD.fechamento_id;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_registros_horas_congelado
    BEFORE UPDATE OR DELETE ON public.registros_horas
    FOR EACH ROW EXECUTE FUNCTION public.impedir_alteracao_publicado();

-- ---------------------------------------------------------------------
-- 13. execucao_erros e chamadas_api
-- ---------------------------------------------------------------------
CREATE TABLE public.execucao_erros (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execucao_id     integer     NOT NULL REFERENCES public.execucoes_extracao(id) ON DELETE CASCADE,
    colaborador_id  integer     REFERENCES public.colaboradores(id) ON DELETE SET NULL,
    etapa           text        NOT NULL,
    http_status     smallint,
    mensagem        text        NOT NULL,
    criado_em       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT execucao_erros_etapa_chk CHECK (etapa IN ('autenticacao', 'sincronizacao', 'calcular', 'mapeamento', 'gravacao'))
);
CREATE INDEX execucao_erros_execucao_idx ON public.execucao_erros (execucao_id);

CREATE TABLE public.chamadas_api (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id   integer     NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    execucao_id  integer     REFERENCES public.execucoes_extracao(id) ON DELETE SET NULL,
    rota         text        NOT NULL,
    http_status  smallint,
    duracao_ms   integer,
    feita_em     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX chamadas_api_cota_idx ON public.chamadas_api (empresa_id, rota, feita_em DESC);

-- ---------------------------------------------------------------------
-- 14. log_auditoria
-- ---------------------------------------------------------------------
CREATE TABLE public.log_auditoria (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   integer     REFERENCES public.usuarios(id) ON DELETE SET NULL,
    empresa_id   integer     REFERENCES public.empresas(id) ON DELETE SET NULL,
    acao         text        NOT NULL,
    entidade     text,
    entidade_id  text,
    dados        jsonb,
    ip           inet,
    criado_em    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX log_auditoria_empresa_idx ON public.log_auditoria (empresa_id, criado_em DESC);

CREATE TABLE public.worker_status (
    nome      text        PRIMARY KEY,
    visto_em  timestamptz NOT NULL DEFAULT now(),
    info      jsonb
);

-- ---------------------------------------------------------------------
-- 15. Escopo de acesso (usado pela API em toda leitura)
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.unidades_permitidas(p_usuario_id integer)
RETURNS SETOF integer
LANGUAGE sql
STABLE
SET search_path = public, pg_catalog
AS $$
    SELECT un.id
      FROM usuarios u
      JOIN unidades un
        ON u.perfil = 'admin'
        OR (u.perfil = 'rh' AND un.empresa_id = u.empresa_id)
     WHERE u.id = p_usuario_id AND u.ativo AND un.ativo
    UNION
    SELECT uu.unidade_id
      FROM usuarios u
      JOIN usuario_unidades uu ON uu.usuario_id = u.id
      JOIN unidades un         ON un.id = uu.unidade_id AND un.ativo AND un.nome_exibicao IS NOT NULL
     WHERE u.id = p_usuario_id AND u.ativo AND u.perfil = 'gestor'
$$;

-- ---------------------------------------------------------------------
-- 16. Segurança Supabase: backend acessa como dono (pg direto);
--     Data API (anon/authenticated) não enxerga nada.
-- ---------------------------------------------------------------------
ALTER TABLE public.empresas            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracoes       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mapeamento_colunas  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unidades            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuarios            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuario_unidades    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.colaboradores       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ciclos              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fechamentos         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.execucoes_extracao  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.execucao_erros      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chamadas_api        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registros_horas     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.log_auditoria       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.worker_status       ENABLE ROW LEVEL SECURITY;
-- (sem policies = negado para quem não é dono/bypassrls)

REVOKE EXECUTE ON FUNCTION public.unidades_permitidas(integer) FROM PUBLIC;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        EXECUTE 'REVOKE ALL ON ALL TABLES    IN SCHEMA public FROM anon, authenticated';
        EXECUTE 'REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated';
        EXECUTE 'REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM anon, authenticated';
        EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES    FROM anon, authenticated';
        EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon, authenticated';
        EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM anon, authenticated';
    END IF;
END $$;

