-- =====================================================================
-- 002 — Separa quem usa o sistema em duas tabelas:
--   usuarios  = equipe Scale IA (perfil 'admin', sem empresa): administra o sistema e vê tudo
--   clientes  = usuários das empresas atendidas (perfil 'rh' ou 'gestor', sempre com empresa)
-- RH e gestores existentes migram para clientes mantendo o mesmo id.
-- Quem fez algo (auditoria, configurações, vínculos) passa a ser registrado
-- em uma de duas colunas: *_usuario (equipe) ou *_cliente.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. clientes
-- ---------------------------------------------------------------------
CREATE TABLE public.clientes (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id         integer     NOT NULL REFERENCES public.empresas(id) ON DELETE RESTRICT,
    nome               text        NOT NULL,
    email              text,
    cpf                varchar(11),
    senha              text        NOT NULL,
    perfil             text        NOT NULL DEFAULT 'gestor',
    ativo              boolean     NOT NULL DEFAULT true,
    deve_trocar_senha  boolean     NOT NULL DEFAULT true,
    token_versao       integer     NOT NULL DEFAULT 0,
    ultimo_login_em    timestamptz,
    criado_em          timestamptz NOT NULL DEFAULT now(),
    atualizado_em      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT clientes_perfil_chk    CHECK (perfil IN ('rh', 'gestor')),
    CONSTRAINT clientes_cpf_chk       CHECK (cpf IS NULL OR cpf ~ '^[0-9]{11}$'),
    CONSTRAINT clientes_login_chk     CHECK (email IS NOT NULL OR cpf IS NOT NULL),
    CONSTRAINT clientes_id_empresa_uk UNIQUE (id, empresa_id)
);
CREATE UNIQUE INDEX clientes_email_lower_uk ON public.clientes (lower(email));
CREATE UNIQUE INDEX clientes_cpf_uk         ON public.clientes (cpf) WHERE cpf IS NOT NULL;
CREATE INDEX        clientes_empresa_idx    ON public.clientes (empresa_id);

CREATE TRIGGER trg_clientes_atualizado_em
    BEFORE UPDATE ON public.clientes
    FOR EACH ROW EXECUTE FUNCTION public.definir_atualizado_em();

INSERT INTO public.clientes (id, empresa_id, nome, email, cpf, senha, perfil, ativo, deve_trocar_senha,
                             token_versao, ultimo_login_em, criado_em)
     OVERRIDING SYSTEM VALUE
SELECT u.id, u.empresa_id, u.nome, u.email, u.cpf, u.senha, u.perfil, u.ativo, u.deve_trocar_senha,
       u.token_versao, u.ultimo_login_em, coalesce(u.criado_em, now())
  FROM public.usuarios u
 WHERE u.perfil IN ('rh', 'gestor');

SELECT setval(pg_get_serial_sequence('public.clientes', 'id'),
              greatest((SELECT coalesce(max(id), 0) FROM public.clientes), 1));

-- ---------------------------------------------------------------------
-- 2. Vínculo gestor ↔ unidades (substitui usuario_unidades)
-- ---------------------------------------------------------------------
CREATE TABLE public.cliente_unidades (
    cliente_id          integer     NOT NULL,
    unidade_id          integer     NOT NULL,
    empresa_id          integer     NOT NULL,
    criado_por_usuario  integer     REFERENCES public.usuarios(id) ON DELETE SET NULL,
    criado_por_cliente  integer     REFERENCES public.clientes(id) ON DELETE SET NULL,
    criado_em           timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (cliente_id, unidade_id),
    CONSTRAINT cliente_unidades_cliente_fk FOREIGN KEY (cliente_id, empresa_id)
        REFERENCES public.clientes (id, empresa_id) ON DELETE CASCADE,
    CONSTRAINT cliente_unidades_unidade_fk FOREIGN KEY (unidade_id, empresa_id)
        REFERENCES public.unidades (id, empresa_id) ON DELETE CASCADE,
    CONSTRAINT cliente_unidades_autor_chk CHECK (criado_por_usuario IS NULL OR criado_por_cliente IS NULL)
);
CREATE INDEX cliente_unidades_unidade_idx ON public.cliente_unidades (unidade_id);

INSERT INTO public.cliente_unidades (cliente_id, unidade_id, empresa_id, criado_por_usuario, criado_por_cliente, criado_em)
SELECT uu.usuario_id, uu.unidade_id, uu.empresa_id,
       CASE WHEN autor.perfil = 'admin' THEN uu.criado_por END,
       CASE WHEN autor.perfil IN ('rh', 'gestor') THEN uu.criado_por END,
       uu.criado_em
  FROM public.usuario_unidades uu
  LEFT JOIN public.usuarios autor ON autor.id = uu.criado_por;

-- ---------------------------------------------------------------------
-- 3. Autoria que pode ser da equipe ou de um cliente
-- ---------------------------------------------------------------------
ALTER TABLE public.configuracoes
    ADD COLUMN atualizado_por_cliente integer REFERENCES public.clientes(id) ON DELETE SET NULL;
UPDATE public.configuracoes c
   SET atualizado_por_cliente = c.atualizado_por, atualizado_por = NULL
  FROM public.usuarios u
 WHERE u.id = c.atualizado_por AND u.perfil IN ('rh', 'gestor');
ALTER TABLE public.configuracoes
    ADD CONSTRAINT configuracoes_autor_chk CHECK (atualizado_por IS NULL OR atualizado_por_cliente IS NULL);

ALTER TABLE public.log_auditoria
    ADD COLUMN cliente_id integer REFERENCES public.clientes(id) ON DELETE SET NULL;
UPDATE public.log_auditoria a
   SET cliente_id = a.usuario_id, usuario_id = NULL
  FROM public.usuarios u
 WHERE u.id = a.usuario_id AND u.perfil IN ('rh', 'gestor');
ALTER TABLE public.log_auditoria
    ADD CONSTRAINT log_auditoria_autor_chk CHECK (usuario_id IS NULL OR cliente_id IS NULL);

-- Ajuste de gatilho (ciclos) e disparo manual (execuções) são ações só da equipe:
-- referências a clientes, se existirem, viram NULL pelo ON DELETE SET NULL abaixo.

-- ---------------------------------------------------------------------
-- 4. Escopo de acesso: agora recebe o tipo de quem pergunta
-- ---------------------------------------------------------------------
DROP FUNCTION public.unidades_permitidas(integer);

CREATE FUNCTION public.unidades_permitidas(p_tipo text, p_id integer)
RETURNS SETOF integer
LANGUAGE sql
STABLE
SET search_path = public, pg_catalog
AS $$
    -- equipe Scale IA: todas as unidades ativas
    SELECT un.id
      FROM usuarios u
      JOIN unidades un ON un.ativo
     WHERE p_tipo = 'equipe' AND u.id = p_id AND u.ativo
    UNION
    -- RH: unidades ativas da própria empresa
    SELECT un.id
      FROM clientes c
      JOIN unidades un ON un.empresa_id = c.empresa_id AND un.ativo
     WHERE p_tipo = 'cliente' AND c.id = p_id AND c.ativo AND c.perfil = 'rh'
    UNION
    -- gestor: só as unidades vinculadas
    SELECT cu.unidade_id
      FROM clientes c
      JOIN cliente_unidades cu ON cu.cliente_id = c.id
      JOIN unidades un         ON un.id = cu.unidade_id AND un.ativo AND un.nome_exibicao IS NOT NULL
     WHERE p_tipo = 'cliente' AND c.id = p_id AND c.ativo AND c.perfil = 'gestor'
$$;

REVOKE EXECUTE ON FUNCTION public.unidades_permitidas(text, integer) FROM PUBLIC;

-- ---------------------------------------------------------------------
-- 5. usuarios passa a ser só a equipe
-- ---------------------------------------------------------------------
DROP TABLE public.usuario_unidades;
DELETE FROM public.usuarios WHERE perfil IN ('rh', 'gestor');

ALTER TABLE public.usuarios
    DROP CONSTRAINT usuarios_perfil_empresa_chk,
    DROP CONSTRAINT usuarios_id_empresa_uk,
    DROP CONSTRAINT usuarios_perfil_chk;
DROP INDEX IF EXISTS public.usuarios_empresa_idx;
ALTER TABLE public.usuarios DROP COLUMN empresa_id;
ALTER TABLE public.usuarios
    ALTER COLUMN perfil SET DEFAULT 'admin',
    ADD CONSTRAINT usuarios_perfil_chk CHECK (perfil = 'admin');

-- ---------------------------------------------------------------------
-- 6. Um mesmo e-mail/CPF não pode existir nas duas tabelas (login único)
-- ---------------------------------------------------------------------
CREATE FUNCTION public.garantir_login_unico()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_catalog
AS $$
DECLARE
    v_outra text := CASE WHEN TG_TABLE_NAME = 'usuarios' THEN 'clientes' ELSE 'usuarios' END;
    v_existe boolean;
BEGIN
    EXECUTE format(
        'SELECT EXISTS (SELECT 1 FROM public.%I WHERE ($1 IS NOT NULL AND lower(email) = lower($1))
                                               OR ($2 IS NOT NULL AND cpf = $2))', v_outra)
       INTO v_existe
      USING NEW.email, NEW.cpf;
    IF v_existe THEN
        RAISE EXCEPTION 'E-mail ou CPF já usado em %', v_outra USING ERRCODE = 'unique_violation';
    END IF;
    RETURN NEW;
END $$;

CREATE TRIGGER trg_usuarios_login_unico
    BEFORE INSERT OR UPDATE OF email, cpf ON public.usuarios
    FOR EACH ROW EXECUTE FUNCTION public.garantir_login_unico();
CREATE TRIGGER trg_clientes_login_unico
    BEFORE INSERT OR UPDATE OF email, cpf ON public.clientes
    FOR EACH ROW EXECUTE FUNCTION public.garantir_login_unico();

REVOKE EXECUTE ON FUNCTION public.garantir_login_unico() FROM PUBLIC;

-- ---------------------------------------------------------------------
-- 7. Segurança Supabase (mesma regra da 001: Data API não enxerga nada)
-- ---------------------------------------------------------------------
ALTER TABLE public.clientes         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cliente_unidades ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        EXECUTE 'REVOKE ALL ON public.clientes, public.cliente_unidades FROM anon, authenticated';
        EXECUTE 'REVOKE ALL ON FUNCTION public.unidades_permitidas(text, integer) FROM anon, authenticated';
        EXECUTE 'REVOKE ALL ON FUNCTION public.garantir_login_unico() FROM anon, authenticated';
    END IF;
END $$;
